@version: 4.8

# Template untuk memformat log yang akan dikirim ke stdout Docker
template t_isostamp {
    template("[SYSLOG] $MSGHDR$MSG\n");
};

# Opsi-opsi global untuk syslog-ng
options {
    file-template(t_isostamp);
    chain_hostnames(off);
    flush_lines(0);
    use-dns(no);
    use_fqdn(no);
    owner("application");
    group("application");
    perm(0640);
    stats(freq(0));
};

source s_src {
    unix-stream("/var/run/syslog-ng.sock");
    internal();
};

filter f_filter {
    not facility(auth, authpriv);
};

destination d_all {
    pipe(
        "/docker.stdout",
        disk-buffer(
            disk-buf-size(1048576),
            flow-control-window-bytes(65536), # Buffer di disk (1MB)
            reliable(yes),         # Pastikan tidak ada log yang hilang
            dir("/var/lib/syslog-ng/buffer") # Folder untuk buffer. Pastikan bisa ditulis!
        )
    );
};

log {
    source(s_src);
    filter(f_filter);
    destination(d_all);
};
