services:
  moodle:
    image: app-moodle-${APP_NAME}
    restart: unless-stopped
    userns_mode: keep-id
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: ${MOODLE_REPLICAS:-1}
      resources:
        limits:
          cpus: '1.50'
          memory: 1024M
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    volumes:
      - ./moodle:/var/www/html:z
      - ./moodle_data:/var/www/moodledata:z
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health.php"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 10s
  db:
    image: mariadb:11
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: ${DB_REPLICAS:-1}
      resources:
        limits:
          cpus: '1.50'
          memory: 1024M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: ${TZ}
    volumes:
      - ./docker/mysql/datadir:/var/lib/mysql:z
      - ./docker/mysql/config/my.cnf:/etc/my.cnf:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 10s
