[group:moodle]
programs=moodle-cron,moodle-adhoc
priority=25

[program:moodle-cron]
command = /bin/bash -c 'while true; do /usr/local/bin/php /var/www/html/admin/cli/cron.php; sleep 60; done'
process_name=%(program_name)s
startsecs = 0
autostart = true
autorestart = true
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
stderr_logfile=/dev/null
stderr_logfile_maxbytes=0

[program:moodle-adhoc]
command = /bin/bash -c 'while true; do /usr/local/bin/php /var/www/html/admin/cli/adhoc_task.php --execute --keep-alive=59; sleep 60; done'
process_name=%(program_name)s
startsecs = 0
autostart = true
autorestart = true
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
stderr_logfile=/dev/null
stderr_logfile_maxbytes=0
